tsunamods-codes/7th-Heaven

SeventhHeavenUI/Classes/GameLauncher.cs

Added a potential fix for some of the Code 5 fix issues as the Code 5 fix seems to be causing problems with WDM drivers in windows 10.

CodeFix fix for EasyHook problem

---

7thWrapperLib/Wrap.cs
SeventhHeavenUI/Classes/GameLauncher.cs

Reverts tsunamods-codes/7th-Heaven#23

Revert "Bugfix/hexd ordering"

---

7thHeaven.Code/7thHeaven.Code.csproj
7thHeaven.Code/ConfigSettings.cs
7thHeaven.Code/FFNxConfigManager.cs
7thHeaven.Code/Sys.cs
SeventhHeavenUI/Classes/FFNxDriverUpdater.cs
SeventhHeavenUI/ViewModels/MainWindowViewModel.cs
SeventhHeavenUI/Windows/ConfigureGLWindow.xaml.cs

- Expose a new class that centralizes all the logic management: FFNxConfigManager
- The configuration can now be accessed via Sys.FFNxConfig
- 7th Defaults ( inherited from the Game Driver UI xml files ) will be automatically set on each driver update

FFNx: Improve the overall configuration management lifecycle

---

SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.es.xml
SeventhHeavenUI/Resources/Languages/StringResources.es.xaml

Revised a little more the texts of the Driver .xml with strings (2-3 lines), and revised totally the strings used in 7th Heaven application.

Update/Translate english text strings into spanish language or improve them.

---

SeventhHeavenUI/Resources/7H_GameDriver_UI.xml

Updated Game Driver Settings

---

7thHeaven.Code/FFNxConfigManager.cs
7thHeaven.Code/FileDownloadTask.cs
7thHeaven.Code/Sys.cs
7thWrapperLib/Profile.cs
SeventhHeavenUI/Classes/GameLauncher.cs
SeventhHeavenUI/ViewModels/CatalogViewModel.cs

Fixed Issues when a download fails meaning a user can not restart the download without restarting 7th heaven.

Fix download issues

---

SeventhHeavenUI/Classes/GameLauncher.cs

Fixed the messaging for Mod Oder after or before so it shows the correct error not the incompatible error

Fixing the wrong messages being displayed

---

SeventhHeavenUI/Classes/DateTimeComparer.cs

Always saw that sorting by release date was not working properly

CatalogUI: Fix release date sorting bug

---

SeventhHeavenUI/Resources/7H_GameDriver_UI.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.br.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.de.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.es.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.fr.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.gr.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.it.xml
SeventhHeavenUI/Windows/ConfigureGLWindow.xaml

PR for issue #78 
Anyway, all the other languages still have the old UI of 7th 2.3.3.

GameDriverUI: Add steam compatibility checkbox and increase height of window

---

SeventhHeavenUI/Classes/GameLauncher.cs

Still easy for users to find. Less intrusive.

Change crash zip location.

---

SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.es.xml
SeventhHeavenUI/Resources/Languages/StringResources.es.xaml

A few updates about spanish translation in strings and GameDriver xml files.

A few updates about spanish translation.

---

SeventhHeavenUI/Resources/StringResources.xaml

make it more informative and less accusatory towards any particular mod.

Edit language of allowmodtorun

---

7thWrapperLib/Wrap.cs

Do this only if extraFolders and conditionalFolders of the mod are empty.
I also refactored it.

Wrap: Add files in base folder to mapped files

---

7thWrapperLib/Profile.cs
7thWrapperLib/VFile.cs
7thWrapperLib/Wrap.cs
SeventhHeavenUI/Classes/GameLauncher.cs

Seems to work, although I got some Code 5 error of EasyHook sometimes while testing

Wrap: Optimize mapping of game files to mods files

---

7thHeaven.Code/RegistryHelper.cs

Hello, This fix creates the temporal folder if doesnt exist
Thanks

Creates Temp folder if not exist

---

7thWrapperLoader/dllmain.cpp

…ibraries are missing.
Signed-off-by: eve-atum <c.zakelj@ieee.org>

7thWrapperLoader: Tweak the .NET error message

---

SeventhHeavenUI/Classes/FFNxDriverUpdater.cs

Remind users to reconfigure their driver after upgrading/downgrading FFNx.  We get this question often enough, and Kuraudo asked nicely...

UI: Tweak driver upgrade/downgrade message

---

README.md

Add steps to use VSCode as IDE using an extension (still in preview)

README: Add steps for VSCode as IDE

---

SeventhHeavenUI/Resources/Help/index.html
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.de.xml

Includes both nuadaxxx's fix, as well as updates the help file to credit all three members of the de overhaul team

Gardening: One line exceeded display window constraints

---

.iss/CodeDependencies.iss

Related: https://github.com/dotnet/core/issues/9671

iss: Update dotnetcli domain
