SeventhHeavenUI/SeventhHeavenUI.csproj
SeventhHeavenUI/sign.ps1

Added Powershell script that makes signing easier
1. Allows files to be supplied at top of the script
2. Allows developers to modify and use their own certificates
3. Allows password-protected certificates without prompt from windows with first argument

Powershell Script for singing, default to Tsunamods Team Certificate

---

SeventhHeavenUI/Classes/PrimaryScreen.cs
SeventhHeavenUI/Classes/SupportedResolution.cs
SeventhHeavenUI/Resources/7H_GameDriver_UI.xml
SeventhHeavenUI/SeventhHeavenUI.csproj
SeventhHeavenUI/Windows/ConfigureGLWindow.xaml.cs

Update so that the config file only holds the info for the options for dropdown not that values, the values are now pulled from the WIM system in windows by querying for the CIM_VideoControllerResolution, as we don't support refresh rates this has been removed and a singleton system put in place to prevent duplicate resolutions because of refresh rates
This is to implement feature request #5

Added support for reading support resolutions from the WIM system

---

SeventhHeavenUI/Windows/ControlMappingWindow.xaml.cs

tell the user that the save has been successful when they are saving to an already custom control set, other wise same prompt as current where it will tell them to create a custom control map configuration

Controls Saved feed back

---

7thHeaven.Code/FFNxConfigManager.cs
7thWrapperLib/Profile.cs
SeventhHeavenUI/Classes/GameLauncher.cs

Fix also minor bug happening while backupping/restoring the FFNx.toml file through the FFNxConfigManager class.
An example of mod using this new node:
```xml
<?xml version="1.0"?>
<ModInfo>
<Author>Julian Xhokaxhiu</Author>
<Version>0.1</Version>
<Description>FFNx Config override example</Description>
<Link>https://github.com/julianxhokaxhiu/FFNx</Link>
<FFNxConfig>
<ff7_footsteps>true</ff7_footsteps>
</FFNxConfig>
</ModInfo>
```
The behavior is documented as following when you launch the game:
-> It will backup your current `FFNx.toml`
-> The code will loop through every mod you have enabled ( top to bottom ) and will apply every new config found in each `mod.xml` if any
-> It will run the game as usual
-> When the game is closed it will restore the previously backupped `FFNx.toml` file …

7th: Add support for FFNxConfig inside the mod.xml file

---

7thWrapperLib/Profile.cs
SeventhHeavenUI/Classes/GameLauncher.cs

This PR is a follow up of #29 and introduces the behavior we discussed the last time, allowing modders to decide when to enable a specific flag in FFNx, based on what the user configured inside of their own mod panel.
Through this new patch we now do support two possible scenarios.
A modder wants to set always this flag, no matter what. The syntax to achieve it remains the same as specified in #34 
```xml
<?xml version="1.0"?>
<ModInfo>
<Author>Julian Xhokaxhiu</Author>
<Version>0.1</Version>
<Description>FFNx Config override example</Description>
<Link>https://github.com/julianxhokaxhiu/FFNx</Link>
<FFNxConfig>
<ff7_footsteps>true</ff7_footsteps>
</FFNxConfig>
</ModInfo>
```
A modder wants to set a flag, but only when a given option has been enabled. The syntax to achieve this scenario …

7th: Customize FFNx Flag setting behavior

---

7thHeaven.Code/Sys.cs

`Sys.InstallPath` is `null` when initializing the property `PathToFFNxToml` on a cold boot.
It will contain a value only once the user will click "Save" on the General Settings window.
Fixes #35

Fix crash on startup

---

SeventhHeavenUI/Resources/7H_GameDriver_UI.xml

Proper defaults for music and SFX for use without any mods. 7h currently has music and sfx set to VGMStream=true by default. This wasn't an issue before because the false flags were being inherited from FFNx until now. We've already had a couple people confused why they're getting no SFX when they're not using a SFX mod. Same with music... Now we have the ability for mods to activate these flags only when necessary as well.

Proper SFX and Music defaults for 7H_GameDriver_UI.xml

---

SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.de.xml

There was a left over flag which doesn't exist on FFNx anymore, and apparently only in this language was forgotten to be cleaned up.

Fix Game driver window crashing only when using German language

---

SeventhHeavenUI/Classes/GameLauncher.cs

This fixes a small bug that happens when you change the `FFNx.toml` file while having 7th opened and then you launch the game.
**Expected Behavior:**
7th launches the game using the `FFNx.toml` flags state, it creates a backup, it applies mod desired config and it launches the game. User expectes to have mod loaded correctly and its custom flags set before launching ( for eg. `trace_all = yes` ).
**Current Behavior:**
If I set the flag `trace_all = yes` and then I launch the game, 7th will keep in memory the flag as false ( as it parsed the file on 7th launch ), and when it will backup the file and apply new configuration flags it will keep the flag as `false` despite you having it set to true.

FFNx: Always use the latest config state available on disk

---

SeventhHeavenUI/Resources/7H_GameDriver_UI.xml

Move animated textures to graphics tabs, Add Advanced Lighting to Graphics tab, Add Analogue Controls to Advanced tab

Add Analogue and Lighting toggles

---

7thHeaven.Code/FFNxConfigManager.cs
7thHeaven.Code/Sys.cs
7thWrapperLib/Profile.cs
SeventhHeavenUI/Classes/GameLauncher.cs

Added support for mods to use config array for FFNx is done though groups of  `<item>` for the properties.
E.G
```xml
<disable_animated_textures_on_field ATA="1">
<item>ancnt1</item>
<item>ancnt2</item>
<item>ancnt3</item>
<item>ancnt4</item>
<item>blin1</item>
</disable_animated_textures_on_field>
```

Ffnx config updates

---

.iss/installer.iss

Currently there is a step to launch the app once the installer is complete. If /SILENT or /VERYSILENT is used, this happens automatically.
Added a piece to skip launching the app on a silent install, to streamline Linux installs (https://github.com/tsunamods-codes/7th-Heaven/issues/19)

Skip app launch if silent install is requested

---

SeventhHeavenUI/Resources/7H_GameDriver_UI.xml

Supports higher scaling, adds suggested values which have been determined via testing by Vertex and Chris, Removed odd values higher than 1x as suggested by Vertex as they suboptimal can cause artefacts, 1x is preserved for those who want close as possible to original rendering.

Update Internal Scaler Options

---

SeventhHeavenUI/Resources/7H_GameDriver_UI.xml

Also added entry for auto-attack.
I was going to use 'Square/X', "Circle/B' etc. but then you run into a problem when you get down to speed hack: 
'L3, then L1/R1/LB/RB'... or even further; 'L3/LS, then L1/R1/LB/RB'
So yeah, PS buttons only as it was before.

Update controller shortcut info.

---

7thWrapperLib/Wrap.cs

In this way, when we try to map a file to a mod file, we are sure the mapped files in profile is initialized

Move initialization of mapped files into CreateFileW hook function

---

7thWrapperLib/Wrap.cs

There was a problem with FFNx FF7 music not loading. It was because IROs that do not use folder of mod.xml, starts from root IRO folder, so there was no need to get the substring starting from index 1. 
Regarding the counterpart folder mods, there is no need in that case.

Fix fileKey string for IRO that start from root mod folder

---

7thWrapperLib/RuntimeVar.cs

This type is initialized only once for the entire game session with a random value. For example, it is used with `RandomVarOnce:name:256`; it will generate a random variable named 'name' that ranges from 0 to 256

RuntimeVar: Add RandomVarOnce type

---

7thWrapperLib/RuntimeVar.cs

Other than adding a new variable RandomVar, the RandomVarOnce has been updated to use the same data structure of RandomVar. The idea behind this variable is to have a variable that holds a random value that can be rerolled. The reroll strategy is based on two conditions:
- The lookup of the conditional folder of this `RuntimeVar` has just started (this is controlled by the `locked` attribute, which is locked after the first lookup and unlocked after it is resolved)
- A delta time in seconds has been passed from the last reroll If these two conditions are satisfied, the random variable is rerolled, and the last reroll timestamp is updated. This can be used with the notation:
```xml
<RuntimeVar Var="RandomVar:{varName}:{size}:{deltaTime}" Values="217..218" />
```
where:
- `{varName}` has to …

RuntimeVar: Add variable RandomVar that holds a random value

---

7thHeaven.Code/RegistryHelper.cs

Since there is a problem with having registry paths with double backslash, I removed the replace adding another backslash and only added a new backslash to the end of the path if required.
I tested it by changing the path of FF7 install dir, and it is working.

RegistryHelper: Fix double backslash path

---

7thHeaven.Code/RegistryHelper.cs

The issue previously is that `new Guid(currentValue as byte[])` requires currentValue to be exactly 16 bytes of length, otherwise it throws an error. With this change, even if the current guid value is wrong (e.g. less than 16 byte or null), it will be overwritten.

RegistryHelper: Fix equality registry value for Guid

---

SeventhHeavenUI/Classes/UpdateChecker.cs

Robocopy is broken in Wine/Proton, which has forced us to use some awkward workarounds to get 7th Heaven's updater working on the Steam Deck.
After trying and failing for several hours to find a workaround that persists after a proton update, I had no success. Even if we can get it working, I think it's a lot more sensible to just change the behaviour of the temporary `update.bat` that 7th Heaven uses to update itself, rather than have a wrapper on the Steam Deck just to handle something as simple as moving files.
This PR simply replaces the use of `robocopy` with `xcopy`. Since `xcopy` is deprecated, I attempted to use `move` but was met with a sharing violation that I couldn't find a way around.
I tested this on both Windows and Steam Deck, and it seems to function as expected but I …

Update using xcopy instead of robocopy

---

SeventhHeavenUI/Classes/GameLauncher.cs

There was some talk in Discord about using the profile.txt that is created with `ViewProfileDetails()` in `OpenProfileViewModel.cs` than providing the profile.xml, since the former is much more readable.
There may be a better place in the codebase for this but I didn't go too deep because this is only running when the game crashes anyway. Open to suggestions.

Convert profile.xml to profile.txt for crashlog

---

SeventhHeavenUI/Classes/UpdateChecker.cs

Starting this PR we will use the EXE installer instead of the ZIP release to manage upgrades.
This will allow us to scale better in future even when the stacks are bumped.
The user behavior remains basically the same:
1. 7thHeaven downloads the EXE
2. It will run it in silent mode
- If missing dependencies are not installed the installer will prompt the user to install them
- if dependencies are met it will continue the installation as usual on the path where 7th is currently being run
3. It will automatically restart 7th Heaven after the upgrade

UpdateChecker: Use the installer to auto-update

---

7thHeaven.Code/FFNxConfigManager.cs
SeventhHeavenUI/Resources/7H_GameDriver_UI.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.br.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.de.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.es.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.fr.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.gr.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.it.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.ja.xml

This commit will remove the advanced flags for music and FFMpeg do reduce the confusion on the user.
The new interface will look like this in the Advanced section:
The FFMpeg movie flag was unnecessary as for FF7 there was never the case to disable that in the first place.
The Music flag will instead be managed by looking if the current installation has ogg files in "music/vgmstream". If not, it will fallback on using MIDI by default. If a mod is installed, it will automatically override this flag using the mod.xml layer.

SeventhHeavenUI: Auto manage use_external_music

---

SeventhHeavenUI/Classes/GameLauncher.cs

This PR should hopefully fix all the reported cases of "configuration stuck" after launching the game and crashing.

GameLauncher: Ensure FFNx.toml is restored on all possible cases

---

SeventhHeavenUI/Resources/Languages/StringResources.ja.xaml
SeventhHeavenUI/Resources/StringResources.xaml

Rephrase the update text to indicate that we are downloading and running the new version's installer, not opening a browser window.

Gardening: Refine Core update message

---

SeventhHeavenUI/Resources/Help/index.html

Nuada would prefer a different credential, and noticed that npp had eaten the "br" tags

Gardening: Username preference and missing <CRLF>

---

.iss/installer.iss

Switching from Canary to Stable does not seem to work because of a missing flag in the Inno config.
This change will allow downgrading using the new updater method.
I tested it by building 7th Heaven in Release mode, updating to stable through the UI, and then using the Inno script to build a new installer.  I also changed the Inno script to Release mode so it would point to the correct path (I changed this back before pushing).
Then I updated my build to canary and ran the stable release installer from GitHub and ran 7th Heaven. Still on 3.3.0.1.
Then I ran the `mysetup.exe` from the `.iss/Output` folder and launched 7th Heaven and it seems to install 3.3.0.0 properly.
I think a new installer needs to be built for the current stable release before this will actually work.

iss: Allow downgrades via 7th

---

SeventhHeavenUI/Resources/7H_GameDriver_UI.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.br.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.de.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.es.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.fr.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.gr.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.it.xml
SeventhHeavenUI/Resources/Languages/7H_GameDriver_UI.ja.xml

Cranking MSAA too high causes visual artifacts on 4k screens, and increases the likelihood of bgfx device disconnects on older GPU hardware.

SeventhHeavenUI: Remove 8x/16x MSAA as selectable options

---

AppUI/Resources/StringResources.xaml

We haven't had a true pirate to make fun of in Discord for a very long time, but altered/corrupt EXE files show up fairly frequently.  Adjust the message to better reflect this.

Gardening: Adjust piracy/exe verification message
